### ISSUE TITLE
Errors with Pasink in Kodi

### ISSUE THREAD

**Issue by lilomaster** [Heckie75/kodi-addon-pasink#2]
Hi:

I've been trying to use your addon with Kodi 18.3 on an ubuntu 19.04 based stick computer with bluetooth connection (I think it is a broadcom). The strange thing is that I have another computer with more or less the same configuration, and there it works like a charm. It is an Intel core i3 with an atheros bluetooth device, whereas the computer where the plugin is failing is an Intel atom stick PC.

When I run pasink -l, I get the following output:

awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,
awk: line 1: syntax error at or near ,

Default sink:
awk: line 11: syntax error at or near ,
awk: line 16: syntax error at or near ,
awk: line 20: syntax error at or near ,
awk: line 24: syntax error at or near ,
awk: line 30: syntax error at or near ,

Plugged Alsa card devices:
awk: line 11: syntax error at or near ,
awk: line 16: syntax error at or near ,
awk: line 20: syntax error at or near ,
awk: line 24: syntax error at or near ,
awk: line 30: syntax error at or near ,

Sinked Bluetooth A2DP device:
awk: line 11: syntax error at or near ,
awk: line 16: syntax error at or near ,
awk: line 20: syntax error at or near ,
awk: line 24: syntax error at or near ,
awk: line 30: syntax error at or near ,

Paired Bluetooth A2DP devices:

Volume:
awk: line 1: syntax error at or near ,
awk: line 11: syntax error at or near ,
awk: line 16: syntax error at or near ,
awk: line 20: syntax error at or near ,
awk: line 24: syntax error at or near ,
awk: line 30: syntax error at or near ,

bluez is installed, I installed expect as well. 

Please, help.

Thanks.

**Comment by lilomaster** [comment]
OK, I solved the problem. I had to install gawk, which is necessary for pasink to work properly. there was another awk program that seemed to behave differently and didn't provide the information needed by pasink.

Thanks, anyway.

**Comment by Heckie75** [comment]
Correct, it was my first thought that gawk was not installed.

**Comment by Heckie75** [comment]
I have updated the hints according pre-conditions.
