### ISSUE TITLE
Doesn't work in Kodi 18.9.0

### ISSUE THREAD

**Issue by lprobsth** [Heckie75/kodi-addon-pasink#4]
Addon throws the following error in Kodi 18.9.0 on Ubuntu 20.04.1 LTS

`2020-11-06 22:06:17.566 T:139684297541376   ERROR: GetDirectory - Error getting plugin://plugin.audio.pasink/
2020-11-06 22:09:41.967 T:139682022237952   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.KeyError'>
                                            Error Contents: 'id'
                                            Traceback (most recent call last):
                                              File "/home/username/.kodi/addons/plugin.audio.pasink/addon.py", line 538, in <module>
                                                browse(path)
                                              File "/home/username/.kodi/addons/plugin.audio.pasink/addon.py", line 447, in browse
                                                build_dir_structure()
                                              File "/home/username/.kodi/addons/plugin.audio.pasink/addon.py", line 331, in build_dir_structure
                                                displayname = get_displayname(sink=default_sink)
                                              File "/home/username/.kodi/addons/plugin.audio.pasink/addon.py", line 236, in get_displayname
                                                if sink["id"] in aliases:
                                            KeyError: 'id'
                                            -->End of Python script error report<--`

**Comment by Heckie75** [comment]
Actually I run this addon with Kodi 18.9 and have no problem. The problem is something else. 

Please do the following.

1. Open a terminal and change to lib directory of the addon where the ```pasink``` script is located, e.g. ```~/.kodi/addons/plugin.audio.pasink/lib```

Run ```pasinnk```script as follows:
```
$ ./pasink --list-all
```

My output is:
```
Default sink:
0       R       module-alsa-card.c      Aureon Dual USB Digital Stereo (IEC958) alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.iec958-stereo  100%

Plugged Alsa card devices:
0       R       module-alsa-card.c      Aureon Dual USB Digital Stereo (IEC958) alsa_output.usb-C-Media_Electronics_Inc._USB_PnP_Sound_Device-00.iec958-stereo  100%

Sinked Bluetooth A2DP device:

Paired Bluetooth A2DP devices:
00:1D:DF:52:F1:91       paired  PHILIPS AS111
00:1D:DF:51:53:2B       paired  PHILIPS AS111
00:1D:DF:8B:D4:D1       paired  PHILIPS AS111
```

Please send me your output.

**Comment by lprobsth** [comment]
Hey,

thanks for your answer. The output looks like this:

```
Default sink:
Connection failure: Connection terminated

Plugged Alsa card devices:
Connection failure: Connection terminated

Sinked Bluetooth A2DP device:
Connection failure: Connection terminated
Connection failure: Connection terminated

Paired Bluetooth A2DP devices:
0C:A6:94:7D:CA:16       paired  PHILIPS AEA2700
```

In the audio mixer I only see one audio device and it's selected as default sink. But pasink doesn't show it.
I followed this answer on askubuntu [https://askubuntu.com/a/78179](https://askubuntu.com/a/78179) and installed paprefs for showing multiple sinks in audio mixer at the same time.

After restarting pulseaudio the output looks like this:
```
Default sink:
0       S       module-alsa-card.c      Built-in Audio Digital Stereo (HDMI)    alsa_output.pci-0000_00_1b.0.hdmi-stereo        100%

Plugged Alsa card devices:
0       S       module-alsa-card.c      Built-in Audio Digital Stereo (HDMI)    alsa_output.pci-0000_00_1b.0.hdmi-stereo        100%

Sinked Bluetooth A2DP device:

Combined sink:
1       S       module-combine-sink.c   Simultaneous output to Built-in Audio Digital Stereo (HDMI)     combined        100%

Paired Bluetooth A2DP devices:
0C:A6:94:7D:CA:16       paired  PHILIPS AEA2700
```

Switching the default sink with your addon works again. I don't know if restarting pulseaudio resolved the problem (I rebooted several times before). Or if the default sink was somehow messed up before...
