### ISSUE TITLE
By default in Raspberry Pi OS, permission error resources/lib/pasink

### ISSUE THREAD

**Issue by Slugsh** [Heckie75/kodi-addon-pasink#5]
Hi,

**Thank you** for this script. Easy way to change bluetooth devices on Raspberry Pi OS (without exiting to desktop).

I just wanted to let you know that this script didn't work out of the box, I had to add executable permission to resources/lib/pasink to make it work.

I'm not running Kodi as sudo.

**Comment by Heckie75** [comment]
Thank you for this information. I guess that there isn't any chance to change it, since I provide it as zip file.

**Comment by Slugsh** [comment]
Agree, maybe provide it as installable plugin at some point? Or add mention to readme about permissions. Either way, great work! Been enjoying this addon
